# Use a base image with a lightweight web server
FROM nginx:alpine

# Copy your HTML and CSS files into the container
COPY . /usr/share/nginx/html


# # Use a base image with Node.js installed
# FROM node:14

# # Set the working directory in the container
# WORKDIR D:\Important Stuff\Computacenter\Proiect\wildrydes-site

# # Copy the package.json and package-lock.json to the container
# COPY package*.json ./

# # Install the application dependencies
# RUN npm install

# # Copy the rest of the application files to the container
# COPY . .

# # Expose the port that your application will listen on (if needed)
# EXPOSE 80

# # Define the command to run your application
# CMD ["npm", "start"]
